### PR TITLE
Add direct access to text transformation matrix to API

### PR DESCRIPTION
**Pull request by doctormo**

### CODE REVIEW

**Comment by jpakkane** [comment]
All lists that come from the PDF spec should be in the same order in code as they are in the spec. In this case `cmd_XX`es should be in alphabetical order.

**Comment by doctormo** [comment]
Fixed.

**Comment by jpakkane** [comment]
It turns out that I hade made a typo. The command is called `Tm`, not `TM`.

**Comment by jpakkane** [comment]
I fixed existing code. Well, all the one instance of it.

Also, the names used for arguments should mirror the ones used in the PDF spec. For some reason the text matrix uses `a`, `b, `c`, `d`, `e` and `f` instead of `m1-m6` so this should also (existing code does that).

**Comment by doctormo** [comment]
Fixed

**Pull request merged**
