### PR TITLE
Fix name of author variable

### PR DESCRIPTION
**Pull request by doctormo**

### CODE REVIEW

**Comment by doctormo** [comment]
I've added a second commit which allows the producer to be customised, you may or may not have feelings about how this should be handled. I'd be open to however you'd like to handle it.

**Comment by jpakkane** [comment]
I'd really prefer not to provide a way to customize the producer field. That is the one place of "advertising space" that we have int entire PDF and also important for statistical purposes (i.e. X percent of all PDFs used for purpose Y are created with library Z). Changing the producer tag should require a fork with actual changes that are not upstream.

If you look at Adobe products, they also do exactly this. The creator tag is set to the application name like Illustrator and the producer is "Adobe PDF libraries x.y" or smth.

**Comment by doctormo** [comment]
I somewhat agree, it's only difficult because my code is also producing the pdf, so it's a blended experience.

The main tool is Inkscape, but the creator is the pdfout python extension. I wonder if it's possible to do a prefix or suffix like is done with web browsers. Such as `CapyPdf; Svg2Pdf` or something similar. Our many layered sandwich of code doesn't fit well into this Adobe dynamic.

**Comment by jpakkane** [comment]
You can put that in the creator field with something like `Inkscape / Foo exporter`.

**Comment by doctormo** [comment]
The second commit is removed, this is now just the original fix.

**Pull request merged**
