### PR TITLE
Add image interpolation to raster image support, include python and C…

### PR DESCRIPTION
**Pull request by doctormo**
Example of what this looks like:  [rasters.pdf](https://github.com/jpakkane/capypdf/files/12507232/rasters.pdf)

This is a change to the API.

### CODE REVIEW

**Comment by jpakkane** [comment]
This brings up a design decision which I have punted thus far, namely that of booleans in the public API. In other projects I have been bitten by having booleans, since almost every single time it has turned out that later we needed some third value. In fact, in this case there arguably already is a need for three values: `true`, `false` and `do not write a dictionary entry for this image` the last one being the default action. This would imply an enum, which is also more readable, especially if there are many arguments to avoid tag soup lie `function(true, false, false, true);`.

Any opinions on this?

It should be noted that the PDF alliance is currently working on adding new stuff like HDR to PDF. It's not inconceivable that they would add more interpolation methods (bicubic etc).

**Comment by doctormo** [comment]
Enum was my second thought and I'll change it to an enum right away.

**Comment by doctormo** [comment]
Fixed

**Comment by jpakkane** [comment]
I suspect that we are going to need to create a proper object for image properties. But we'll take care of that later.

**Pull request merged**
