### PR TITLE
Add the lines svg as a generated test

### PR DESCRIPTION
**Pull request by doctormo**
OK this is going to need some back and forth to figure out what the right way of doing this is going to be. I've constructed the recorded module which will be included in pdfout's source code here [recorder.zip](https://github.com/jpakkane/capypdf/files/12504432/recorder.zip) you will see the template section which defines where the generated code should go.

In this merge request you can see an example test (not a proper python test) and it generates the lines pdf file that I attached to the previous MR.

### CODE REVIEW

**Comment by jpakkane** [comment]
Dunno how much of this is makes sense for you but looking at the output it seems to me that limiting float precision to something like three decimals should be enough and also it would be great to get it to use `push_gstate` instead of manual `q` and `Q` commands.

**Comment by doctormo** [comment]
Fixed

**Comment by jpakkane** [comment]
Any particular reason why you are doing:

```
with capypdf.StateContextManager(ctx0) as state0:
```

as opposed to

```
with ctx0.push_gstate():
```

The `StateContextManager` is an internal class. Users should not even know that it exists. There is also no need to store the result in a named variable because there are no methods you can call on it (as opposed to `ctx`, which you always need to access).

Anyway, I edited this a bit by hand and put in master as a test.

**Comment by doctormo** [comment]
It says not to edit it :wink: 

The StateContextManager is being used as a base class, it's very useful as a class and not a function call. I would like to promote it to first class part of the API, especially since it's pure python so shouldn't effect the capi at all.

The variables are because it's generating this, so it doesn't know for sure if something is going to be used while it's printing it out.

Want to close this MR?

**Comment by jpakkane** [comment]
> I would like to promote it to first class part of the API, especially since it's pure python so shouldn't effect the capi at all.

What advantage would that bring? Currently it is just a much longer way of typing the same thing.

**Comment by doctormo** [comment]
You can't inherit from a function.

**Comment by jpakkane** [comment]
But what problem are you solving by inheriting from the context manager class?

**Comment by doctormo** [comment]
Further context management.

**Comment by jpakkane** [comment]
Not in general, but specific. As specific as you can possibly get. As in "I want to achieve X, so I want to do Y with Z".

**Comment by doctormo** [comment]
Best to see the api being used in the wild: https://gitlab.com/inkscape/extras/extension-pdf/-/blob/main/pdfout.py#L534

I think it'll be easier to just copy the code into my own codebase then attempt to argue about it, the cost of this conversation is way higher than the code involved.

**Comment by doctormo** [comment]
I may have been operating under the assumption that you were already looking at my python code, if this isn't the case, then I apologise for being annoyed about something you couldn't have done anything more reasonable about.

**Comment by jpakkane** [comment]
I hadn't read that before, sorry. That's why I asked.

That seems like a reasonable use case, so we could indeed provide something for it. But on the other hand, as you say, that is a very small amount of code, so having downstream reimplement it is not _that_ big of a deal. The real question is how common would this requirement be, but unfortunately we can't know that until after the library has been adopted by several projects. :(

**Comment by doctormo** [comment]
I tried to have a look and see if there's PEP advice on context managers. There's no strong opinion between the two forms. Classes are the default, are slightly more obvious and self-documenting when introspection. Functions can have embedded context and can make bespoke classes (that's what the contextmanager decorator is doing)

The capypdf API contains many root class uses, i.e. the API doesn't all hang off of the generator class in a big tree of in-context calls (Color, Options, PageProperties). But it sometimes does hang off of the generator (draw_context, load_font, load_image, etc). So the existing design isn't instructive about which would be used.

I'm a proponent of "why not both", if the API for one is actually just a wrapper for the other. Of course if you choose to just have a class, you should move it into the def so it's private.

**Comment by jpakkane** [comment]
> the API doesn't all hang off of the generator class in a big tree of in-context calls (Color, Options, PageProperties). But it sometimes does hang off of the generator

My original idea was that "data only" classes like page properties object can be created and used freely as they are not tied to any particular generator. More heavy duty classes like DrawingContext are generated inside the generator object as they are strongly tied to it.

Then after a while I realized that does not really work as Color is tied to the generator when using ICC colors (but not when using other colors). So I don't have a particularly good answer here.

**Pull request closed without merging**
